### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by TesterRXL** [Dr-Noob/PACYBITS_FUT20_Hack#1]
Hey! Pacybits closed a while ago and "MADFUT" Is the new Pacybits right now. It is from the same developers if im sure. I'm making my own script right now and it's going pretty good. My last goals are having 100% collection and 50 duplicates per player. That's how i came across your post. I have problems with making the xml file as an argument while running the python script and because of missing permissions. . I have a rooted S8+.

**Comment by Dr-Noob** [comment]
Hey, I have created a new project for the MADFUT app. You can check it in: https://github.com/Dr-Noob/MADFUT22_Hack. I hope you find it interesting.

Closing the issue
